Controllers/MotorController.cs
using FactoryMethod_Grupo1.Data;
using FactoryMethod_Grupo1.FactoryMethod;
using FactoryMethod_Grupo1.Models;
using Microsoft.AspNetCore.Mvc;

namespace FactoryMethod_Grupo1.Controllers
{
    public class MotorController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MotorController(ApplicationDbContext context)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));
        }

        public IActionResult Index()
        {
            var motores = _context.Motores.ToList();
            return View(motores);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(string tipoMotor, string especificaciones)
        {
            // Crear un nuevo objeto Motor
            var motor = new Motor
            {
                Tipo = tipoMotor,
                Especificaciones = especificaciones
            };


            _context.Motores.Add(motor);
            _context.SaveChanges();

            return RedirectToAction("Success");
        }

        public IActionResult Success()
        {
            return View();
        }
    }
}

Views/Mueble/Create.cshtml
@{
    ViewData["Title"] = "Crear Motor";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Create" asp-controller="Motor" method="post">
    <div class="form-group">
        <label for="tipoMotor">Tipo de Motor</label>
        <select id="tipoMotor" name="tipoMotor" class="form-control">
            <option value="Electrico">Motor Eléctrico</option>
            <option value="Combustion">Motor de Combustión</option>
        </select>
    </div> <br />

    <div class="form-group">
        <label for="especificaciones">Especificaciones</label>
        <textarea class="form-control" id="especificaciones" name="especificaciones" placeholder="Ingresa las especificaciones del motor"></textarea>
    </div> <br />

    <button type="submit" class="btn btn-primary">Crear Motor</button>
</form>

Views/Mueble/Index.cshtml
@{
    var motores = Model;
}

<h1>Motores</h1>
<br />

<button type="button" class="btn btn-dark mb-3" onclick="location.href='@Url.Action("Create", "Motor")'">Crear Motor</button>
<br />
<br />

<table class="table table-dark">
    <thead>
        <tr>
            <th>#</th>
            <th>Tipo</th>
            <th>Especificaciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var motor in motores)
        {
            <tr>
                <td>@motor.Id</td>
                <td>@motor.Tipo</td>
                <td>@motor.Especificaciones</td>
            </tr>
        }
    </tbody>
</table>